import type { DocsPage, Locale } from "./content-types.ts";

export type { DocSection, DocsPage, Locale, TextPair } from "./content-types.ts";
export { locales } from "./content-types.ts";

export const pages: Record<Locale, DocsPage> = {
  en: {
    locale: "en",
    languageLabel: "English",
    switchLabel: "简体中文",
    menuLabel: "Open menu",
    nav: [
      { label: "Quick start", value: "quick-start" },
      { label: "Concepts", value: "concepts" },
      { label: "Web UI", value: "web-ui" },
      { label: "TUI", value: "tui" },
      { label: "Install", value: "release-install" },
      { label: "Config", value: "configuration" },
      { label: "Pi", value: "pi-integration" },
      { label: "Safety", value: "identity-safety" },
      { label: "Templates", value: "templates" },
      { label: "API", value: "api-sdk" },
      { label: "Contributing", value: "contributing" },
    ],
    hero: {
      title: "Realm",
      promise:
        "A local-first AI command center with one beautiful chat window. Talk to 天道 in plain language to create worlds, set rules, run roles, adjudicate, and inspect state — the AI does the work, controls are the rare exception.",
      installLabel: "Install",
      installCommand: "bunx @nicepkg/realm init --template cultivation",
      primaryAction: "Start in 3 commands",
      secondaryAction: "View GitHub",
      proof: ["Bun + TypeScript", "Pi package-first", "Web + TUI", "Binary-ready"],
    },
    valueProps: [
      {
        label: "Local-first",
        value: "Runs entirely on your machine. No cloud account, no data leaving the repo.",
      },
      {
        label: "Natural language first",
        value:
          "One chat window. Say what you want in plain language; the AI runs the action — not a wall of buttons.",
      },
      {
        label: "Real role accounts",
        value: "Each role acts like an account, with audited turns and scoped tools.",
      },
      {
        label: "Web + terminal",
        value: "One runtime, two surfaces. Drive the same world from the browser or the TUI.",
      },
    ],
    preview: {
      chatTitle: "天道",
      emptyPrompt: "Talk to 天道",
      suggestions: [
        "Create a cultivation world",
        "Make Gu Chenfeng want to retreat",
        "What's the world state now?",
      ],
      userMessage: "Create a cultivation world with a sect, a rival, and a master.",
      assistantReply:
        "I'll create the world “Cultivation Realm” with a sect, the rival Gu Chenfeng, and a master role. Review before I write:",
      confirmTitle: "Create world · Cultivation Realm",
      confirmSummary: "+1 world · +3 roles · +1 state schema · risky write",
      confirmAction: "Confirm",
      composer: "Tell 天道…",
    },
    quickStart: {
      title: "Three commands to a running world",
      intro:
        "Realm is useful before you configure real model keys. Start with a deterministic fake runtime, inspect the world, then switch to provider-backed role turns when ready.",
      steps: [
        { label: "Initialize", value: "realm init --template cultivation" },
        { label: "Trust the project", value: "realm trust --tier run-roles" },
        { label: "Open the workspace", value: "realm open --runtime fake" },
      ],
    },
    concepts: {
      title: "The mental model",
      intro:
        "A project owns portable files. A world owns state. Rooms carry conversation. Roles behave like accounts. God is a guarded adjudication surface, not a casual chat contact.",
      nodes: [
        { label: "Project", value: ".agents config, templates, skills, trust boundary" },
        { label: "World", value: "rooms, roles, state schema, visibility and events" },
        { label: "Role", value: "model, prompt skill, memory and scoped tools" },
        { label: "God", value: "typed actions, state patches, audit and rollback evidence" },
      ],
    },
    tui: {
      title: "A conversational commander, not a readline loop",
      intro:
        "The TUI is the same chat window in your terminal: tell 天道 what you want in plain language and the AI runs it. Colon-commands are an optional power-user fast path, not something you have to memorize.",
      lines: [
        "Realm TUI | Cultivation Demo",
        "World: Cultivation Demo | Room: All Hands | Speaking: owner",
        "You: Create a cultivation world with a sect.",
        "天道: I'll create “Cultivation Realm” with a sect. Confirm before I write?",
        "You: Let Gu Chenfeng speak for one turn.",
        "You: What's the world state right now?",
        "Enter send · Ctrl+G God Console · type the confirmation for risky writes",
      ],
    },
    trust: {
      title: "Local-first by default",
      intro:
        "Realm treats repository files as portable truth and keeps secrets, logs, provider keys, and runtime state out of git.",
      bullets: [
        "Project config lives under .agents and can be reviewed like code.",
        "Machine-local settings live in REALM_HOME or ~/.realm.",
        "High-risk actions pass through policy, validation, audit, and confirmation.",
        "Pi package integration is the normal path; subprocess RPC is diagnostic fallback.",
      ],
    },
    examples: {
      title: "Templates that prove behavior",
      intro:
        "Examples are acceptance fixtures: they exercise messaging, state visibility, God actions, role turns, workflow approvals, and replay.",
      items: [
        {
          label: "Cultivation simulation",
          value: "examples/cultivation-sim with roles, visibility, state, skills and events",
        },
        {
          label: "Software company",
          value: "PM, architect, engineer, QA, security and docs roles",
        },
        { label: "Investment council", value: "thesis, risk, conviction and decision-room memory" },
      ],
    },
    sections: [
      {
        id: "release-install",
        eyebrow: "Install / release",
        title: "Use npm, source, or a Bun-built binary",
        body: "The codebase stays Bun + TypeScript end to end. The same CLI can run from source, install from npm, or ship as a Bun binary for machines that should not install a Node toolchain. Release checks build the Web UI, docs, CLI and binary before publication.",
        bullets: [
          "Source: bun run apps/cli/src/index.ts open --runtime fake",
          "Package: npm i -g @nicepkg/realm",
          "Binary: bun run build:binary && ./dist/bin/realm doctor",
          "Docs: bun run build:docs, then deploy with Wrangler when Cloudflare credentials are present.",
          "CI should prove Linux, macOS, Windows, docs, binary smoke, package smoke and Web structure checks before a release is trusted.",
        ],
        code: "bun install\nbun run build\nbun run build:docs\nbun run build:binary\n./dist/bin/realm init --template cultivation\n./dist/bin/realm open --runtime fake",
      },
      {
        id: "configuration",
        eyebrow: "Configuration",
        title: "Files stay reviewable",
        body: "Worlds, roles, room definitions, visibility, state schema, and callable skills are plain files. Config assistants may propose changes, but they apply through patch validation and rollback history.",
        bullets: [
          ".agents/config.yaml is the project entry point.",
          "config.local.yaml, state and logs are local-only.",
          "Config patches carry intent, affected files, risk and recovery context.",
          "High-risk patches require the exact typed confirmation returned by policy.",
          "Apply checks file hashes again so stale previews cannot overwrite newer config.",
        ],
        code: ".agents/\n  config.yaml\n  roles/<role>/role.yaml\n  worlds/<world>/world.yaml\n  worlds/<world>/state.schema.yaml\n  state/ # gitignored\n  logs/  # gitignored",
      },
      {
        id: "web-ui",
        eyebrow: "Web UI",
        title: "One chat window, driven by natural language",
        body: "The first screen is a single beautiful chat window. You talk to the system — 天道/God — in plain language and the AI runs the action: create a world, set a rule, add or adjust a role, run a role turn, adjudicate, or inspect state. Precise controls only appear when a number is faster to type or a risky write needs confirming.",
        bullets: [
          "The home screen is a conversation, not an industrial-control dashboard.",
          "Plain-language intent maps to a real backend action: config-patch proposal, God/state action, role turn, or a read.",
          "Risky writes surface a lightweight inline preview/confirm card right in the chat — never a giant sheet.",
          "After each action the chat reports what happened and the world updates live; drafts survive failure and stay retryable.",
          "Controls are the rare exception — a field or slider only when typing a number beats a sentence.",
        ],
        code: "realm open --runtime fake\n# Say: 创建一个修真世界  -> preview card -> Confirm\n# Say: 让顾辰风心生退意 / 现在世界什么状态?",
      },
      {
        id: "tui",
        eyebrow: "TUI",
        title: "Natural language in the terminal",
        body: "The terminal surface is the same conversation: type what you want in plain language and the AI runs it — create a world, run a role's turn, adjudicate, or inspect state. Colon-commands stay available as an optional fast path for power users, and risky writes still require typed confirmation.",
        bullets: [
          "Plain language is the primary path: 'create a cultivation world', 'let Gu Chenfeng speak', 'what's the world state?'.",
          "Current project, world, room and identity stay visible above the chat.",
          "Ctrl+G opens the guarded God Console; risky writes still need the exact typed confirmation.",
          "Colon-commands (e.g. :run-role) are an optional power-user shortcut, not the way you operate.",
          "Failed sends preserve drafts under the user-local draft store, so nothing is lost on retry.",
        ],
        code: "realm tui --base-url http://127.0.0.1:3737\n# Type: Create a cultivation world with a sect\n# Type: Let Gu Chenfeng speak for one turn  ->  confirm the risky write",
      },
      {
        id: "pi-integration",
        eyebrow: "Pi integration",
        title: "Package-first role turns",
        body: "Realm integrates Pi through package dependencies so normal role turns do not require a global pi executable. The subprocess RPC path exists for diagnostics and compatibility smoke tests.",
        bullets: [
          "Role turns use scoped tools generated from Realm policy.",
          "Trace events record model, usage, tool calls and failures.",
          "Doctor output distinguishes package runtime from subprocess fallback.",
          "Package metadata is recorded on turn events for audit and support.",
          "Explicit provider env input is hermetic and does not merge ambient API keys.",
        ],
        code: "realm doctor --fallback\nrealm open --runtime package\nbun run smoke:real-providers --provider google --timeout-ms 120000",
      },
      {
        id: "identity-safety",
        eyebrow: "Identity safety",
        title: "Role accounts are explicit",
        body: "Speaking as a role is powerful and risky. Realm keeps the visible identity, real operator and audit trail explicit across Web, TUI, API and event store.",
        bullets: [
          "Boss/owner is the default composer identity.",
          "Role takeover uses confirmation and a persistent banner.",
          "God is not a normal chat identity.",
          "Switching worlds resets the speaking identity back to Boss.",
          "Public message APIs ignore caller-supplied real operators and audit the owner.",
        ],
        code: "Boss -> + -> Lei Jun -> Confirm role takeover\nWorld switch -> identity resets to Boss\nGod action -> typed target role confirmation",
      },
      {
        id: "api-sdk",
        eyebrow: "API",
        title: "One runtime, many clients",
        body: "Web, TUI, tests and automation all use the same typed API contracts and client SDK. Domain logic lives in packages, not in React components or terminal rendering.",
        bullets: [
          "Zod contracts define messages, events, patches, settings and simulation.",
          "Client SDK wraps role turns, settings, God actions and workflow endpoints.",
          "Service packages enforce policy and trust independent of UI.",
          "Web and TUI share the same client SDK instead of duplicating domain rules.",
          "Server-sent events and WebSocket streams expose the same event model.",
        ],
        code: "const client = new RealmHttpClient({ baseUrl });\nawait client.sendMessage({ worldId, roomId, content });\nawait client.startRoleTurn(worldId, roomId, roleId);",
      },
      {
        id: "contributing",
        eyebrow: "Governance",
        title: "Open-source project hygiene",
        body: "Realm is designed to be trusted by contributors: explicit dependencies, dependency audits, CI, release checks, conventional changelog direction and screenshot acceptance for UI surfaces.",
        bullets: [
          "bun run check:deps catches ghost dependencies.",
          "CI builds Web, docs, CLI binary and tests.",
          "Changes use conventional commits and keep package dependencies explicit.",
          "Source files stay below 500 lines or get split before more features land.",
          "Agent Browser screenshots are part of UI acceptance, not optional polish.",
        ],
        code: "bun run lint\nbun run check\nbun run build\nbun run smoke:web-ui\nbun run smoke:docs-ui",
      },
    ],
    cta: {
      title: "Build a world inside your repo",
      body: "Start with fake runtime, then add model providers, role skills, world state and policy gates when the project is ready.",
      install: "Install Realm",
      github: "Star on GitHub",
    },
  },
  "zh-CN": {
    locale: "zh-CN",
    languageLabel: "简体中文",
    switchLabel: "English",
    menuLabel: "打开菜单",
    nav: [
      { label: "快速开始", value: "quick-start" },
      { label: "核心概念", value: "concepts" },
      { label: "Web UI", value: "web-ui" },
      { label: "TUI", value: "tui" },
      { label: "安装", value: "release-install" },
      { label: "配置", value: "configuration" },
      { label: "Pi", value: "pi-integration" },
      { label: "身份安全", value: "identity-safety" },
      { label: "模板", value: "templates" },
      { label: "API", value: "api-sdk" },
      { label: "贡献", value: "contributing" },
    ],
    hero: {
      title: "Realm",
      promise:
        "一个本地优先的 AI 指挥中心，第一屏就是一个聊天窗口。用自然语言对「天道」说话，就能创建世界、设定规则、运行角色、裁决和查看状态——AI 负责执行，精细控件只是少数例外。",
      installLabel: "安装",
      installCommand: "bunx @nicepkg/realm init --template cultivation",
      primaryAction: "三条命令启动",
      secondaryAction: "查看 GitHub",
      proof: ["Bun + TypeScript", "Pi 包优先", "Web + TUI", "可打包二进制"],
    },
    valueProps: [
      { label: "本地优先", value: "完全在本机运行，无需云账号，数据不离开仓库。" },
      {
        label: "自然语言优先",
        value: "只有一个聊天窗口。用大白话说出你要什么，AI 就去执行——不是一堆按钮。",
      },
      { label: "真正的角色账号", value: "每个角色都像一个账号，回合可审计、工具受限授权。" },
      { label: "Web 与终端", value: "同一套运行时，两个界面。浏览器或终端都能驱动同一个世界。" },
    ],
    preview: {
      chatTitle: "天道",
      emptyPrompt: "对「天道」说点什么",
      suggestions: ["创建一个修真世界", "让顾辰风心生退意", "现在世界什么状态?"],
      userMessage: "创建一个有宗门、对手和师父的修真世界。",
      assistantReply: "我来创建世界「修真界」，包含宗门、对手顾辰风和一位师父角色。写入前请确认：",
      confirmTitle: "创建世界 · 修真界",
      confirmSummary: "+1 世界 · +3 角色 · +1 状态 schema · 危险写入",
      confirmAction: "确认",
      composer: "对天道说……",
    },
    quickStart: {
      title: "三条命令启动一个世界",
      intro:
        "Realm 不要求你一开始就配置真实模型 key。先用确定性的 fake runtime 看清世界结构，之后再切换到真实 provider 跑角色。",
      steps: [
        { label: "初始化", value: "realm init --template cultivation" },
        { label: "信任项目", value: "realm trust --tier run-roles" },
        { label: "打开工作区", value: "realm open --runtime fake" },
      ],
    },
    concepts: {
      title: "你需要记住的模型",
      intro:
        "项目负责可迁移文件，世界负责状态，房间承载对话，角色像独立账号。上帝是有门槛的裁判界面，不是普通聊天联系人。",
      nodes: [
        { label: "Project", value: ".agents 配置、模板、skill、信任边界" },
        { label: "World", value: "房间、角色、状态 schema、可见性和事件" },
        { label: "Role", value: "模型、提示词 skill、记忆和受控工具" },
        { label: "God", value: "typed action、状态 patch、审计和回滚证据" },
      ],
    },
    tui: {
      title: "终端里的对话式指挥官，不是 readline 循环",
      intro:
        "TUI 就是装进终端里的同一个聊天窗口：用大白话对「天道」说出你要什么，AI 就去执行。冒号命令只是给高级用户的可选快捷方式，不需要背。",
      lines: [
        "Realm TUI | 修真 Demo",
        "World: 修真 Demo | Room: 全员群 | Speaking: owner",
        "你：创建一个有宗门的修真世界。",
        "天道：我来创建「修真界」，包含一个宗门。写入前请确认？",
        "你：让顾辰风发言一回合。",
        "你：现在世界什么状态？",
        "Enter 发送 · Ctrl+G 上帝控制台 · 危险写入需输入确认文本",
      ],
    },
    trust: {
      title: "默认本地优先",
      intro: "Realm 把仓库文件当成可迁移真相，把密钥、日志、provider key 和运行时状态留在本机。",
      bullets: [
        "项目配置在 .agents 下，像代码一样接受 review。",
        "机器本地设置在 REALM_HOME 或 ~/.realm。",
        "高风险动作经过策略、校验、审计和确认。",
        "Pi 包集成是常规路径；subprocess RPC 只是诊断兜底。",
      ],
    },
    examples: {
      title: "模板必须证明行为",
      intro:
        "示例不是摆设，而是验收夹具：它们要覆盖消息、状态可见性、上帝动作、角色 turn、工作流审批和回放。",
      items: [
        { label: "修真模拟", value: "examples/cultivation-sim，含角色、可见性、状态、技能和事件" },
        { label: "软件公司", value: "PM、架构师、工程师、QA、安全和文档角色" },
        { label: "投资委员会", value: "论点、风险、置信度和决策室记忆" },
      ],
    },
    sections: [
      {
        id: "release-install",
        eyebrow: "安装 / 发布",
        title: "支持 npm、源码和 Bun 二进制",
        body: "代码栈从头到尾保持 Bun + TypeScript。同一个 CLI 可以从源码运行、通过 npm 安装，也可以打成 Bun 二进制给不想装 Node 工具链的机器用。发布前必须构建 Web、docs、CLI 和 binary。",
        bullets: [
          "源码：bun run apps/cli/src/index.ts open --runtime fake",
          "包安装：npm i -g @nicepkg/realm",
          "二进制：bun run build:binary && ./dist/bin/realm doctor",
          "文档：bun run build:docs；有 Cloudflare 凭证时再用 Wrangler 部署。",
          "发布前要证明 Linux、macOS、Windows、docs、binary smoke、package smoke 和 Web 结构检查都通过。",
        ],
        code: "bun install\nbun run build\nbun run build:docs\nbun run build:binary\n./dist/bin/realm init --template cultivation\n./dist/bin/realm open --runtime fake",
      },
      {
        id: "configuration",
        eyebrow: "配置",
        title: "文件必须可审查",
        body: "世界、角色、房间、可见性、状态 schema 和可调用 skill 都是普通文件。配置助手可以提案，但落盘必须经过 patch 校验和回滚历史。",
        bullets: [
          ".agents/config.yaml 是项目入口。",
          "config.local.yaml、state 和 logs 只留在本机。",
          "配置 patch 带意图、影响文件、风险和恢复上下文。",
          "高风险 patch 必须输入 policy 返回的精确确认文本。",
          "应用前会重新检查文件哈希，避免旧预览覆盖新配置。",
        ],
        code: ".agents/\n  config.yaml\n  roles/<role>/role.yaml\n  worlds/<world>/world.yaml\n  worlds/<world>/state.schema.yaml\n  state/ # gitignored\n  logs/  # gitignored",
      },
      {
        id: "web-ui",
        eyebrow: "Web UI",
        title: "第一屏就是一个聊天窗口，用自然语言操作",
        body: "第一屏就是一个干净的聊天窗口。你用自然语言对系统——「天道」——说话，AI 就执行动作：创建世界、设定规则、加角色或调角色、运行角色回合、裁决、查看状态。只有在输入数值更快、或需要确认危险写入时，才会出现精细控件。",
        bullets: [
          "首屏是一段对话，不是工业控制面板。",
          "一句大白话映射到真实后端动作：配置补丁提案、上帝/状态动作、角色回合，或一次读取。",
          "危险写入只在聊天里弹出一张轻量的预览/确认卡片，绝不是一个巨大的 sheet。",
          "每个动作之后聊天会反馈发生了什么、世界实时更新；草稿在失败后保留并可重试。",
          "控件是少数例外——只有当输入一个数值比说一句话更快时才出现一个输入框或滑块。",
        ],
        code: "realm open --runtime fake\n# 说：创建一个修真世界  -> 预览卡片 -> 确认\n# 说：让顾辰风心生退意 / 现在世界什么状态?",
      },
      {
        id: "tui",
        eyebrow: "TUI",
        title: "终端里也用自然语言操作",
        body: "终端界面就是同一段对话：用大白话说出你要什么，AI 就去执行——创建世界、运行角色回合、裁决，或查看状态。冒号命令作为给高级用户的可选快捷方式保留，危险写入依然需要输入确认文本。",
        bullets: [
          "自然语言是主路径：「创建一个有宗门的修真世界」「让顾辰风发言一回合」「现在世界什么状态？」。",
          "当前项目、世界、房间和身份始终显示在聊天上方。",
          "Ctrl+G 打开有门槛的上帝控制台；危险写入仍需输入精确确认文本。",
          "冒号命令（如 :run-role）是给高级用户的可选快捷方式，不是你操作的方式。",
          "发送失败会把草稿保存在用户本地，重试时不丢内容。",
        ],
        code: "realm tui --base-url http://127.0.0.1:3737\n# 输入：创建一个有宗门的修真世界\n# 输入：让顾辰风发言一回合  ->  确认危险写入",
      },
      {
        id: "pi-integration",
        eyebrow: "Pi 集成",
        title: "角色回合走包优先",
        body: "Realm 通过包依赖集成 Pi，普通角色 turn 不依赖全局 pi 可执行文件。subprocess RPC 只用于诊断和兼容性冒烟。",
        bullets: [
          "角色 turn 使用 Realm policy 生成的受控工具。",
          "Trace 记录模型、用量、工具调用和失败原因。",
          "doctor 输出区分包运行时和 subprocess fallback。",
          "角色事件会记录包运行时元数据，便于审计和排障。",
          "显式 provider env 是 hermetic 的，不会混入环境变量里的 API key。",
        ],
        code: "realm doctor --fallback\nrealm open --runtime package\nbun run smoke:real-providers --provider google --timeout-ms 120000",
      },
      {
        id: "identity-safety",
        eyebrow: "身份安全",
        title: "角色账号必须显式",
        body: "代替角色发言是高风险动作。Realm 在 Web、TUI、API 和事件日志里都保留显示身份、真实操作者和审计记录。",
        bullets: [
          "Boss/owner 是默认输入身份。",
          "接管角色需要确认，并显示持续 banner。",
          "上帝不是普通聊天身份。",
          "切换世界会把发言身份重置回 Boss。",
          "公开 message API 会忽略调用方传入的真实操作者，并按 owner 审计。",
        ],
        code: "Boss -> + -> 雷军 -> 确认角色接管\n切换世界 -> 身份重置为 Boss\n上帝动作 -> 输入目标角色 id 确认",
      },
      {
        id: "api-sdk",
        eyebrow: "API",
        title: "一个运行时，多种客户端",
        body: "Web、TUI、测试和自动化都使用同一套类型化 API 合同和 client SDK。领域逻辑放在 packages 里，不塞进 React 组件或终端渲染。",
        bullets: [
          "Zod 合同定义消息、事件、patch、设置和模拟。",
          "Client SDK 封装角色 turn、设置、上帝动作和工作流端点。",
          "Service packages 在 UI 之外强制执行 policy 和 trust。",
          "Web 和 TUI 共享同一个 client SDK，不重复实现领域规则。",
          "SSE 和 WebSocket 暴露同一个事件模型。",
        ],
        code: "const client = new RealmHttpClient({ baseUrl });\nawait client.sendMessage({ worldId, roomId, content });\nawait client.startRoleTurn(worldId, roomId, roleId);",
      },
      {
        id: "contributing",
        eyebrow: "治理",
        title: "开源项目要经得起审查",
        body: "Realm 必须让贡献者信任：显式依赖、依赖审计、CI、release 检查、conventional changelog 方向，以及 UI 截图验收。",
        bullets: [
          "bun run check:deps 防止幽灵依赖。",
          "CI 构建 Web、docs、CLI binary 并运行测试。",
          "改动使用 conventional commits，并保持 package 依赖显式。",
          "源码文件保持 500 行以内，继续扩展前先拆模块。",
          "Agent Browser 截图是 UI 验收的一部分，不是可选润色。",
        ],
        code: "bun run lint\nbun run check\nbun run build\nbun run smoke:web-ui\nbun run smoke:docs-ui",
      },
    ],
    cta: {
      title: "在你的仓库里启动一个世界",
      body: "先用 fake runtime 跑通，再按项目成熟度增加模型 provider、角色 skill、世界状态和策略门槛。",
      install: "安装 Realm",
      github: "去 GitHub 点 Star",
    },
  },
};
